server:
  # port: 8888
  # servlet:
  #   context-path: /
  error:
    whitelabel:
      enabled: false
    path: /error
    include-exception: false
    include-stacktrace: always

logging:
  level:
    org:
      springframework:
        # security: debug
        # web: debug
      # hibernate: debug

spring:
  profiles:
  - local
  devtools:
    livereload:
      enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    # initialization-mode: always
    # url: jdbc:h2:mem:testdb
    # username: sa
    # password: test
    # driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aptzip?serverTimezone=Asia/Seoul
    username: aptzip
    password: aptziproot
    tomcat:
      initial-size: 151
    dbcp2:
      remove-abandoned-on-borrow: true
      remove-abandoned-timeout: 60
      log-abandoned: true
    platform: mysql
    # initialize:
    #   true : deprecated
  # batch:
  #   initialize-schema: always
  session:
    store-type: none
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
  #     settings:
  #       web-allow-others: true
  http:
    log-request-details: true
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    mode: HTML
    check-template-location: true
  # mvc:
  #   static-path-pattern: /static/**
  # resources:
  #   static-locations:
  #   - classpath:/static/
  #   add-mappings: true
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

env:
  aptzip:
    test: test용 글자입니다.
---
server:
  error:
    whitelabel:
      enabled: false
    path: /error
    include-exception: false
    include-stacktrace: always

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
      hibernate: debug

spring:
  profiles:
  - server
  devtools:
    livereload:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aptzip?serverTimezone=Asia/Seoul
    username: aptzip
    password: aptziproot
    initialization-mode: embedded
    tomcat:
      initial-size: 151
    dbcp2:
      remove-abandoned-on-borrow: true
      remove-abandoned-timeout: 60
      log-abandoned: true
    platform: mysql
  batch:
    initialize-schema: never
  session:
    store-type: none
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  http:
    log-request-details: true
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    mode: HTML
    check-template-location: true
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration