INSERT INTO TB_ROLE (ROLE) VALUES ('ADMIN');
INSERT INTO TB_ROLE (ROLE) VALUES ('USER');

INSERT INTO TB_USER (ID, EMAIL, PASSWORD, SING_UP_DATE, USERNAME, ROLE) VALUES (AUTO_INCREMENT, 'qwe@qwe.qwe', '$2a$10$FUGG6CFHmsptQ0KXebvv2.J9DM7lFpJSUWJtVUKyeq0bkQehdcUMq', NOW(), 'qwe', 'USER');
INSERT INTO TB_USER (ID, EMAIL, PASSWORD, SING_UP_DATE, USERNAME, ROLE) VALUES (AUTO_INCREMENT, 'asd@asd.asd', '$2a$10$oAuT9QNVZe2e5nIZlkqAUOoYgsJDtX5WeYPRmQ5m.eSien2cca/he', NOW(), 'asd', 'ADMIN');